CXX := g++
CXXFLAGS := -g -Wall

all: cpp_ns01 cpp_ns02

cpp_ns01:
	$(CXX) $(CXXFLAGS) -o cpp_ns01 cpp_ns01.cpp

cpp_ns02:
	$(CXX) $(CXXFLAGS) -o cpp_ns02 cpp_ns02.cpp

clean:
	rm -rf cpp_ns01 cpp_ns02