CXX := g++ -std=c++11 #启动c++编译器
CXXFLAGS := -g -Wall

all: cpp_function01 cpp_function02

cpp_function01:
	$(CXX) $(CXXFLAGS) -o cpp_function01 cpp_function01.cpp

cpp_function02:
	$(CXX) $(CXXFLAGS) -o cpp_function02 cpp_function02.cpp

clean:
	rm -rf cpp_function01 cpp_function02