CXX := g++ -std=c++11 #启动c++编译器
CXXFLAGS := -g -Wall

all: cpp_express01 cpp_express02 cpp_express03

cpp_express01:
	$(CXX) $(CXXFLAGS) -o cpp_express01 cpp_express01.cpp

cpp_express02:
	$(CXX) $(CXXFLAGS) -o cpp_express02 cpp_express02.cpp

cpp_express03:
	$(CXX) $(CXXFLAGS) -o cpp_express03 cpp_express03.cpp

clean:
	rm -rf cpp_express01 cpp_express02 cpp_express03